# Generated by Django 3.2.16 on 2023-01-13 19:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='allergens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Celery'), (1, 'Crustaceans'), (2, 'Fish'), (3, 'Milk'), (4, 'Mustard'), (5, 'Peanuts'), (6, 'Soya'), (7, 'Gluten'), (8, 'Eggs'), (9, 'Lupin'), (10, 'Molluscs'), (11, 'Nuts'), (12, 'Sesame Seeds'), (13, 'Sulphur Dioxide')]), size=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Food'), (1, 'Drink'), (2, 'Breakfast'), (3, 'Lunch'), (4, 'Dinner'), (5, 'Desert'), (6, 'Tacos'), (7, 'Enchiladas'), (8, 'Tostadas'), (9, 'Chilaquiles'), (10, 'Huevos Rancheros'), (11, 'Machaca'), (12, 'Discada'), (13, 'Burritos'), (14, 'Menudo'), (15, 'Tamales'), (16, 'Quesadilla'), (17, 'Esquites'), (18, 'Fajitas'), (19, 'Carnitas'), (20, 'Chilli Con Carne'), (21, 'Vegetarian'), (22, 'Vegan'), (23, 'Gluten Free')]), size=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Beginner'), (1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Pro')]),
        ),
    ]
