# Generated by Django 3.2.16 on 2023-01-13 20:26

from django.db import migrations, models
import recipeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_auto_20230113_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=recipeapp.models.ModifiedArrayField(base_field=models.IntegerField(choices=[(0, 'Food'), (1, 'Drink'), (2, 'Breakfast'), (3, 'Lunch'), (4, 'Dinner'), (5, 'Desert'), (6, 'Tacos'), (7, 'Enchiladas'), (8, 'Tostadas'), (9, 'Chilaquiles'), (10, 'Huevos Rancheros'), (11, 'Machaca'), (12, 'Discada'), (13, 'Burritos'), (14, 'Menudo'), (15, 'Tamales'), (16, 'Quesadilla'), (17, 'Esquites'), (18, 'Fajitas'), (19, 'Carnitas'), (20, 'Chilli Con Carne'), (21, 'Vegetarian'), (22, 'Vegan'), (23, 'Gluten Free')]), size=None),
        ),
    ]
