# Generated by Django 3.2.16 on 2023-01-28 16:55

from django.db import migrations, models
import recipeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0005_alter_recipe_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='allergens',
            field=recipeapp.models.ModifiedArrayField(base_field=models.CharField(choices=[('Celery', 'Celery'), ('Crustaceans', 'Crustaceans'), ('Fish', 'Fish'), ('Milk', 'Milk'), ('Mustard', 'Mustard'), ('Peanuts', 'Peanuts'), ('Soya', 'Soya'), ('Gluten', 'Gluten'), ('Eggs', 'Eggs'), ('Lupin', 'Lupin'), ('Molluscs', 'Molluscs'), ('Nuts', 'Nuts'), ('Sesame Seeds', 'Sesame Seeds'), ('Sulphur Dioxide', 'Sulphur Dioxide')], max_length=100), blank=True, size=None),
        ),
    ]
